services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    image: barrylogen/markdown-image-replacer-frontend:${APP_VERSION}
    ports:
      - "13001:13001"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    image: barrylogen/markdown-image-replacer-backend:${APP_VERSION}
    environment:
      - NODE_ENV=production
      - PORT=13000
      - LOG_LEVEL=info
      - LOG_DIR=/app/logs
      - LOCAL_EXPORT_BASE_DIR=/app/temp/md_img_export
      - IMAGE_DOWNLOAD_DELAY_MS=500
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
