name: CI Build Before Merge

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          cd backend && npm i
          cd ../frontend && npm i

      - name: Build Backend
        run: |
          cd backend
          npm start &
          SERVER_PID=$!

          TIMEOUT=10
          for i in $(seq 1 $TIMEOUT); do
            if nc -z localhost 13000; then
              kill $SERVER_PID
              echo "✅ Backend start OK"
              exit 0
            fi
            sleep 1
          done

          kill $SERVER_PID
          echo "🚨 Backend start failed"
          exit 1

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
