name: CI Build Before Merge

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          cd backend && npm i
          cd ../frontend && npm i

      - name: Build Backend
        run: |
          cd backend
          timeout 10s npm start
          status=$?
          if [[ $status -ne 0 && $status -ne 124 ]]; then
            echo "🚨 Backend start failed with exit code $status"
            exit $status
          fi
          echo "✅ Backend start OK (no errors within 10s)"

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
