name: Docker CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      app_version:
        description: 'version (e.g. 0.0.1)'
        required: true

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      IMAGE_NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}
      IMAGE_REPO_NAME: markdown-image-replacer
      APP_VERSION: ${{ github.event.inputs.app_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push frontend (multi-arch)
        run: |
          docker buildx build \
            --no-cache \
            --platform linux/arm64,linux/amd64 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO_NAME }}-frontend:${{ env.APP_VERSION }} \
            -f frontend/Dockerfile \
            ./frontend \
            --push

      - name: Build & push backend (multi-arch)
        run: |
          docker buildx build \
            --no-cache \
            --platform linux/arm64,linux/amd64 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_REPO_NAME }}-backend:${{ env.APP_VERSION }} \
            -f backend/Dockerfile \
            ./backend \
            --push
